<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Approval-NO-1</name>
   <tag></tag>
   <elementGuidId>fb06d29a-a658-46dd-b9fe-cdc1535e7629</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='List_PAAssociateApprovalLs_0_txtApprovalNo']</value>
   </webElementProperties>
</WebElementEntity>
